version: "3"

services:
  app-order-service:
    depends_on:
      - database
    links:
      - database
    restart: unless-stopped
    build: ./product-service
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'scalable'
    ports:
      - 8081:5000
    volumes:
      - ./product-service:/app
    command: python ./app.py


  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: scalable
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3200:3306'
    expose:
      - '3306'
    volumes:
      - scalable-flask-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/first.sql:ro

  admin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80


volumes:
    scalable-flask-db:
      driver: local